# Deploy UI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-interfaz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-interfaz
  template:
    metadata:
      labels:
        app: ui-interfaz
    spec:
      containers:
      - name: ui-interfaz
        image: ui-interfaz:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ui-interfaz
spec:
  selector:
    app: ui-interfaz
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Deploy Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gateway:1.0
        ports:
        - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
---
# Deploy Shoe
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoe
  template:
    metadata:
      labels:
        app: shoe
    spec:
      containers:
      - name: shoe
        image: shoe:1.0
        ports:
        - containerPort: 1001
---
apiVersion: v1
kind: Service
metadata:
  name: shoe
spec:
  selector:
    app: shoe
  ports:
    - protocol: TCP
      port: 1001
      targetPort: 1001
---
# Deploy Offers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: offers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offers
  template:
    metadata:
      labels:
        app: offers
    spec:
      containers:
      - name: offers
        image: offers:1.0
        ports:
        - containerPort: 1002
---
apiVersion: v1
kind: Service
metadata:
  name: offers
spec:
  selector:
    app: offers
  ports:
    - protocol: TCP
      port: 1002
      targetPort: 1002
