apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoe
  template:
    metadata:
      labels:
        app: shoe
    spec:
      containers:
      - name: shoe
        image: shoe:1.0
        ports:
        - containerPort: 1001
---
apiVersion: v1
kind: Service
metadata:
  name: shoe
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 1001
      nodePort: 30082
  selector:
    app: shoe

