apiVersion: apps/v1
kind: Deployment
metadata:
  name: offers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offers
  template:
    metadata:
      labels:
        app: offers
    spec:
      containers:
      - name: offers
        image: offers:1.0
        ports:
        - containerPort: 1002
---
apiVersion: v1
kind: Service
metadata:
  name: offers
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 1002
      nodePort: 30083
  selector:
    app: offers

