apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-interfaz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-interfaz
  template:
    metadata:
      labels:
        app: ui-interfaz
    spec:
      containers:
      - name: ui-interfaz
        image: ui-interfaz:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ui-interfaz
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
  selector:
    app: ui-interfaz

